export const environment = {
  production: true,
};

export const FCTSDashBoard = {
  WRApiV1: "/api/v1/webreports/",
  WFApiV2: "/api/v2/",
  WFApiV1: "/api/v1/",
  //WRApiV1: "/api/v1/nodes/",
  WRApiV2: "/output",
  getMenuCountExt: "CTASidebarExtCount",
  getDashboardInbox: "35872",
  getUserOverallData: "CTAUserDataDashboard",
  ExternalInbNew: "CTA_Dash_ExtInbNew",
  ExternalFullSearch: "CTA_ExtFullSearch",
  DashboardReportMain: "CTA_DashboardWR",
  BravaURL: "CTA_DocPreview",
  TemplateURL:'CTA_TemplatePreview',
  SearchFilters: "CTA_SearchFilters",
  SenderInfo: "CTA_SenderInfoRO",
  RecipientInfo: "CTA_RecipientInfoRO",
  CCInfo: "CTA_CCInfoRO",
  CoverSectionInfo: "CTA_CoverSectionInfoRO",
  AttachmentSectionInfo: "CTA_AttachSectionInfoRO",
  ExtOrgNameFilter: "CTA_ExtOrgNameFilter",
  TransferAttributes: "CTA_TransferAttributes",
  GetTransferFields: "CTA_GetParticipantInfoByName",
  getcorrespondenceinfoRO: "CTA_GetCorrInfoRO",
  WfAuditReport: "CTA_AuditReportWF",
  TransferAuditReport: "CTA_AuditReportTransfer",
  TransferHistoryTab: "CTA_TransferTab",
  getMenuCountInt: "CTASidebarIntCount",
  createTransfer: "CTA_SetTranferUsers",
  GetCorrRecordData: "CTA_GetCorrRecordData",
  GetCorrFolderName: "CTA_GetCorrFolderName",
  UserCollaborationRO: "CTA_UserCollaborationRO",
  WorkflowCommentsList: "CTA_WFCommentsList",
  CorrConnectionsList: "CTA_CorrConnectionsList",
  PropertiesURL: "PropertiesWidget",
  DefaultPageSize: 15,
  //SetPerformerPermission: "CTA_SetPerformPerm",
  SetPerformerPermission: 'CTA_SetPerformPerm_V2',
  SetStatuses: "CTA_SetStatus",
  OrgChart: "CTA_ORGMD_JSON",
  /* added last time*/
  CheckWFRecall: "FCTS_CheckWFRecall",
  GetTransferUsers: "CTA_GetTransferUsers",
  GetTransRecallData: "FCTS_GetTransRecallData",
  RunTransferRecall: "FCTS_RunTransRecall",
  RunWFRecall: "FCTS_RunWFRecall",
  SendRecallEmail: "FCTS_SendRecallEmail",
  SetDipsAudit: "FCTS_SetDipsAudit",
  SetStatusMultiApprove: "FCTS_SetStatusMultiApprove",
  SetTransStatus: "FCTS_UpdTransStatus",
  GetGlobalConst: "CTA_ConstantsObject",
  UserInfo: "CTA_GetUserInfo",
  searchFieldautoFill: "CTA_SearchFieldAutoFill",
  CoverFolderContents: "CTA_CoverSectionData",
  AttachmentFolderContents: "CTA_AttachmentSection",
  createTempAttachments: "CTA_CreateTempAttachments",
  initiateIncomingWF: "CTA_InitExtIncomingWF",

  GenerateBarcode: "CTA_GenerateCorrCode",
  GetCCUserSet: "CTA_CCDataNew",

  getMenuCountMR: "CTA_SidebarMRCount",
  CCRecallReturnToAS: "FCTS_CCRecall",

  GetUserMailroomPrivelage: "CTA_GetUserMailRPrivelage",
  GetApproverList: "CTA_SelectAttributes",
  GetCoverLettertemplates: "CTA_GetTemplates",
  GetColUserSet: "CTA_UserCollData",
  initiateOutgoingWF: "CTA_InitiateOutgoingWF",
  syncDoc: "syncdoc",
  insertNotes: "CTA_InsertNotes",
  getNotes: "CTA_getNotes",
  getWFTaskInfo: "CTA_GetWFTaskInfo",
  //BaseHref: '/img/fctsangular/fctsapp/',
  SelectAttributes: "CTA_Select_Attributes",
  InsertNewComment: "CTA_InsertNewComment",
  DeleteComment: "CTA_DeleteComment",

  setConnection: "CTA_SetConnection",
  getCorrespondenceFormValues: "CTA_CorrFormValues",
  setSubfolderPerm: "CTA_SetSubfolderPerm",
  documentTranlsation: "CTA_DocumentTranslation",
  copyfromcsurl: "CTA_GetCopyCSURL",
  folderbrowserurl: "CTA_FolderBrowseURL",

  initiateInternalWF: "CTA_InitiateInternalOutgoingWF",
  ProxyInfo: "CTA_ProxyUserInfo",
  // BaseHref: '/img/fctsangular/fctsapp/',
  PerformerInfo: "CTA_PerformerInfo",
  UserGroups: "CTA_UserGroups",

  AddDelegation: "CTA_AddDelegation",
  DelegationsActivator: "CTA_DelegationsActivator",
  CurrentDelegations: "CTA_CurrentDelegations",
  DelegationsInactivator: "CAT_SingleDelegationsInactivator",
  DelegationsReport: "CTA_DelegationsReport",

  CorrespondenceRelated: "CTA_CorrespondenceRelated",
  DeleteConnection: "CTA_DeleteConnection",
  DocumentsRelated: "CTA_DocumentsRelated",
  ConnectionsParentChild: "CTA_ConnectionsParentChild",
  FilesSerch: "CTA_FilesSerch",
  InsertConnection: "		CTA_InsertConnection",
  ConnectionsSearch: "CTA_ConnectionsSearch",
  InsertMultipleConnections: "CTA_InsertMultipleConnections",
  GetParentData: "CTA_GetParentData",
  FolderFiles: "CTA_FolderFiles",
  CorrespondenceRelatedShort: "CTA_CorrespondenceRelatedShort",
  DownloadAttachmentsBox: "CTA_DownloadAttachments",
  CopySelectedFiles: "ExtractAllAttachments",
  SetAttDownloadPermissions: "CTA_SetAttDownloadPermissions",
  ECMDChart: "CTA_ECMDChart",
  ECMDSearch: "CTA_ECDM_Search",
  ExportCorrespondence: "CTA_ExportCorrespondence",
  FilterValuesSearch: "CTA_FilterValuesSearch",
  ApproveData: "CTA_ApproveData",
  MultiAppAutoFill: "CTA_MultiAppAutoFill",
  SetMultiApprovers: "CTA_SetMultiApprovers",
  DistributionSection: "CTA_DistributionSection",
  DistributionsChart: "CTA_DistributionsChart",
  DistributionsChartEmployees: "CTA_DistributionsChartEmployees",
  GetDistributionUsers: "CTA_GetDistributionUsers",
  CloseMe: "%2Fimg%2Fcsui%2Fpages%2Fclose.html",
  GetTeams: "CTA_GetTeams",

  // Admin page reports

  AdminPageStructure: "CTA_AdminPageStructure",
  ORGMasterDataRoles: "CTA_ORGMasterDataRoles",
  ORGMDRoleUsers: "CTA_ORGMDRoleUsers",
  ORGMDRoleUsersAction: "CTA_ORGMDRoleUsersAction",
  ORGMDRoleAllUsers: "CTA_ORGMDRoleAllUsers",
  DepartmentsList: "CTA_DepartmentsList",
  // GetAllUsers: 'CTA_GetAllUsers',
  ORGMDOrgChart: "CTA_ORGMDOrgChart",
  ORGMDOrgChartUsers: "CTA_ORGMDOrgChartUsers",
  ORGMDOrgChartSearch: "CTA_OrgChartSearch",
  ORGMDEditOrganizationalChart: "CTA_ORGMDEditOrganizationalChart",
  ObjectInUse: "CTA_ObjectInUse",
  ORGMDOrgUnitUsers: "CTA_ORGMDOrgUnitUsers",
  ORGMDOrgUnitUsersActions: "CTA_ORGMDOrgUnitUsersActions",
  ORGMDOrgUnitAllUsers: "CTA_ORGMDOrgUnitAllUsers",
  ORGMDOrgChartRoles: "CTA_ORGMDOrgChartRoles",
  ORGMDOrgChartUserRoles: "CTA_ORGMDOrgChartUserRoles",
  ORGMDOrgChartRolesAutocmpl: "CTA_ORGMDOrgChartRolesAutocmpl",
  FCTSSpecificRole: "CTA_FCTSSpecificRole",
  FCTSSpecificRoleTreeUsers: "CTA_FCTSSpecificRoleTreeUsers",
  FCTSSpecificRoleUsers: "CTA_FCTSSpecificRoleUsers",
  FCTSRolesOperations: "CTA_FCTSRolesOperations",
  FCTSSpecificRoleAllUsers: "CTA_FCTSSpecificRoleAllUsers",
  FCTSCommonRoles: "CTA_FCTSCommonRoles",
  FCTSCommonRolesUsers: "CTA_FCTSCommonRolesUsers",
  FCTSCommonRoleAllUsers: "CTA_FCTSCommonRoleAllUsers",
  ECMDChartNodes: "CTA_ECMDChartNodes",
  ECMDChartCounterparts: "CTA_ECMDChartCounterparts",
  ECDMChartDepartments: "CTA_ECDMChartDepartments",
  ECDMChartContacts: "CTA_ECDMChartContacts",
  ECMDNodesSearch: "CTA_ECMDNodesSearch",
  ECMDSearchCounterparts: "CTA_ECMDSearchCounterparts",
  ECMDNodesList: "CTA_ECMDNodesList",
  ECMDEditChart: "CTA_ECMDEditChart",
  ECMDChartCountries: "CTA_ECMDChartCountries",
  ECMDChartStates: "CTA_ECMDChartStates",
  ChartPagination: 200,
  ORGMDOrgUnits: "CTA_ORGMDOrgUnits",
  ORGMDTeams: "CTA_ORGMDTeams",
  ORGMDTeamUser: "CTA_ORGMDTeamUser",
  ORGMDTeamsUserRoles: "CTA_ORGMDTeamsUserRoles",
  ORGMDTeamActions: "CTA_ORGMDTeamActions",
  ORGMDCreateGroup: "CTA_ORGMDCreateGroup",
  ORGMDTeamUsers: "CTA_ORGMDTeamUsers",
  ORGMDTeamAllUsers: "CTA_ORGMDTeamAllUsers",
  ORGMDManageTeamUsers: "CTA_ORGMDManageTeamUsers",
  ORGMDTeamProjects: "CTA_ORGMDTeamProjects",
  ORGMDTeamEmployeeRoles: "CTA_ORGMDTeamEmployeeRoles",
  ORGMDDeleteGroup: "CTA_ORGMDDeleteGroup",

  AdminDelegationUsers: "CTA_AdminDelegationUsers",
  AdminAddDelegationGroup: "CTA_AdminAddDelegationGroup",
  AdminSectDelegationsActivator: "CTA_AdminDelegationsActivator",
  AdminCurrentDelegations: "CTA_AdminCurrentDelegations",
  AdminSingleDelegationsInactivator: "CTA_AdminSingleDelegationsInactivator",
  AdminDelegationsReport: "CTA_AdminDelegationsReport",

  ORGMDUnitDefinition: "CTA_UnitDefinition",
  ORGMDUnitDefinitionActions: "CTA_UnitDefinitionActions",
  ORGMDStrEntityRelationsActions: "CTA_StrEntityRelationsActions",
  ORGMDStrEntityRelations: "CTA_StrEntityRelations",

  ECMDRoles: "CTA_ECMDRoles",
  ECMDRoleUsers: "CTA_ECMDRoleUsers",
  ECMDRoleAllUsers: "CTA_ECMDRoleAllUsers",
  ECMDRoleUsersActions: "CTA_ECMDRoleUsersActions",

  MDActions: "CTA_MDActions",
  MDBaseTypes: "CTA_MDBaseTypes",
  MDCorrespondenceTypes: "CTA_MDCorrespondenceTypes",
  MDDocumentTypes: "CTA_MDDocumentTypes",
  MDDispatchMethods: "CTA_MDDispatchMethods",
  MDPurposes: "CTA_MDPurposes",
  MDPhaseList: "CTA_MDPhaseList",
  MDPriority: "CTA_MDPriority",
  MDRejectReasons: "CTA_MDRejectReasons",
  MDYearList: "CTA_MDYearList",
  MDYear: "CTA_MDYear",
  MDPhysicalLocationList: "CTA_MDPhysicalLocationList",
  MDPhysicalLocation: "CTA_MDPhysicalLocation",
  MDCabinetList: "CTA_MDCabinetList",
  MDRowList: "CTA_MDRowList",
  MDShelfList: "CTA_MDShelfList",
  MDCabinet: "CTA_MDCabinet",
  MDRow: "CTA_MDRow",
  MDShelf: "CTA_MDShelf",
  MDFile: "CTA_MDFile",
  // BaseHref: '/img/fctsangular/fctsapp/',
  BaseHref: "/img/fctsangular/fctsapp/",
  CSUrlShort: "eimsdemo.mannaicorp.com.qa",
  CSUrl: "http://eimsdemo.mannaicorp.com.qa/otcs/cs.exe",
  ConvertDocToPDF: "CTA_ConvertDocToPDF",
};
